[build]
builder = "nixpacks"

[deploy]
startCommand = "mkdir -p /tmp/huggingface && chmod 777 /tmp/huggingface && rm -rf /tmp/huggingface/tmp* && python -m api.main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
